Map<String, String> get arabicMap => {
      "Dark Theme": "مظهر داكن",
      "Home": "القائمة الرئيسية",
      "Categories": "الفئات",
      "Recurring Transactions": "الاجراءات المتكررة",
      "Settings": "الأعدادات",
      "Category": "الفئة",
      "Optional": "اختباري",
      "From": "من",
      "Until": "الى",
      "Forever": "الأبد",
      "Weekly": "اسبوعي",
      ".Monthly": "شهري",
      "Yearly": "سنوي",
      "Daily": "يومي",
      "day": "يوم",
      "week": "اسبوع",
      "month": "شهر",
      "year": "سنة",
      "Choose date": "اختر تاريخ",
      "Today": "اليوم",
      "Add Task": "مهمة جديدة",
      "Do you want to proceed": "هل تريد الاستمرار؟",
      "Category Name": "اسم الفئة",
      "please enter name": "الرجاء ادخال اسم",
      "Add List": "اضافة قائمة",
      "Type": "النوع",
      "Expired": "منتهي الصلاحية",
      "Notes": "ملاحضات",
      "Let's set your App": "هيا لنقم بأعداد التطبيق",
      "Hello": "مرحبا",
      "Almost Done": "سننتهي قريبا",
      "Starts from": "يبدأ من",
      "FUTURE": "مستقبلا",
      "Remove this Task?": "هل تريد حذف هذه المهمة؟",
      "THIS MONTH": "هذا الشهر",
      "Please enter number": "الرجاء ادخال قيمة",
      "Description": "الوصف",
      "Overview": "نظرة عامة",
      "Done": "تم",
      "Final Step": "اخر خطوة",
      "Repeat every": "اعادة كل",
      "RepeatType.Forever": "للابد",
      "RepeatType.Until": "الى",
      "No": "لا",
      "Remove": "حذف",
      "To": "الى",
      "Yes": "نعم",
      "Change App Language": "تغيير لغة التطبيق",
      "Arabic": "العربية",
      "Info": "معلومات",
      "Language": "اللغة",
      "January": "كانون الثاني",
      "February": "شباط",
      "March": "اذار",
      "April": "نيسان",
      "May": "ايار",
      "June": "حزيران",
      "July": "تموز",
      "August": "اب",
      "september": "أيلول",
      "October": "تشرين أول",
      "November": "تشرين ثاني",
      "December": "كانون أول",
      "Change": "تغيير",
      "Report": "تقرير",
      "First": "أول",
      "Second": "ثاني",
      "Third": "ثالث",
      "Forth": "رابع",
      "Week": "الاسبوع",
      "Due in Tommorow": "مستحق غدا",
      "Due in": "مستحق بعد",
      "days": "أيام",
      "Repeat till": "تكرار الى",
      "Preferences": "التفضيلات",
      "Calendar": "التقويم",
      "clear Complete": "مسح المكتملة",
      "Color": "اللون",
      "Priority": "الاهمية",
      "Creat Task": "انشاء مهمة",
      "Notification": "التنبيه",
      "Notifications": "التنبيهات",
      "Creat New Task": "انشاء مهمة جديدة",
      "Theme": "المظهر",
      "Tasks": "المهام",
      "All Tasks": "كل المهام"
    };
