Map<String, String> get englishMap => {
      "Dark Theme": "Dark Theme",
      "Total": "Total",
      "Home": "Home",
      "Categories": "Categories",
      "Optional": "Optional",
      "From": "From",
      "Until": "Until",
      "Forever": "Forever",
      "Weekly": "Weekly",
      "Monthly": "Monthly",
      "Yearly": "Yearly",
      "Daily": "Daily",
      "day": "day",
      "week": "week",
      "month": "month",
      "year": "year",
      "Choose date": "Choose Date",
      "Today": "Today",
      "Add Task": "Add Task",
      "Category Name": "Category Name",
      "please enter name": "please enter name",
      "Add List": "Add List",
      "Type": "Type",
      "Expired": "Expired",
      "Task Note": "Task Note",
      "Let's set your App": "Let's set your App",
      "Hello": "Hello",
      "Almost Done": "Almost Done",
      "Starts from": "Starts from",
      "Remove this Task?": "Remove this Task?",
      "THIS MONTH": "THIS MONTH",
      "Please enter number": "Please enter number",
      "Description": "Description",
      "Overview": "Overview",
      "There is no Transactions here": "There is no Transactions here",
      "Done": "Done",
      "Final Step": "Final Step",
      "Remove this Transaction?": "Remove this Transaction?",
      "No": "No",
      "Remove": "Remove",
      "Repeat every": "Repeat every",
      "RepeatType.Forever": "Forever",
      "RepeatType.Until": "Until",
      "To": "To",
      "Yes": "Yes",
      "Change App Language": "Change App Language",
      "Arabic": "Arabic",
      "Info": "Info",
      "Language": "Language",
      "Change": "Change",
      "January": "January",
      "February": "February",
      "March": "March",
      "April": "April",
      "May": "May",
      "June": "June",
      "July": "July",
      "August": "August",
      "september": "september",
      "October": "October",
      "November": "November",
      "December": "December",
      "Due in Tommorow": "Due in Tommorow",
      "Due in": "Due in",
      "days": "days",
      "Repeat till": "Repeat till",
      "Preferences": "Prefrences",
      "All Tasks": "All Tasks",
      "Calendar": "Calendar",
      "clear Complete": "clear Complete",
      "Color": "Color",
      "Priority": "Priority",
      "Creat Task": "Creat Task",
      "Notification": "Notification",
      "Notifications": "Notifications",
      "Creat New Task": "Creat New Task",
      "Theme": "Theme"
    };
