include: package:effective_dart/analysis_options.yaml
linter:
  rules:
    constant_identifier_names: false
    directives_ordering: false
    file_names: false
    unnecessary_this: false
    prefer_final_in_for_each: false
    avoid_classes_with_only_static_members: false
    avoid_relative_lib_imports: false
    avoid_function_literals_in_foreach_calls: false
    use_setters_to_change_properties: false
    argument_type_not_assignable: true
    prefer_if_elements_to_conditional_expressions: false
    prefer_function_declarations_over_variables: false
    avoid_bool_literals_in_conditional_expressions: false
    public_member_api_docs: false
    lines_longer_than_80_chars: false
    prefer_const_constructors: true
    avoid_print: true
    avoid_catches_without_on_clauses: false
    camel_case_extensions: false
    avoid_equals_and_hash_code_on_mutable_classes: false

analyzer:
  errors:
    missing_required_param: error
    parameter_assignments: error
